1.Write a Python program to input a number, if it is not a number generates an error message.

while True:
    try:
        a = int(input("Input a number: "))
        break
    except ValueError:
        print("\nThis is not a number. Try again...")
        print()
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2.The array element whose index is out of bound and handle the corresponding exception.

a = [1, 2, 3]
try:
    print ("Second element = ",a[1])
    print ("Fourth element = ",a[3])
except:
    print ("An error occurred")
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3.Catching specific exception in Python

def fun(a):
    if a < 4:
        b = a/(a-3)
    print("Value of b = ", b)
try:
    fun(3)
    fun(5)
except ZeroDivisionError:
    print("ZeroDivisionError Occurred and Handled")
except NameError:
    print("NameError Occurred and Handled")
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
4.Raising Exception.

try:
    raise NameError("Hi there")
except NameError:
    print("An exception")
    raise
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
5.Try with else clause

def AbyB(a,b):
    try:
        c=((a+b)/(a-b))
    except ZeroDivisionError:
        print("a/b result in 0")
    else:
        print(c)
AbyB(2.0, 3.0)
AbyB(3.0, 3.0)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
